/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import conexionBD.ConexionOracle;
import controlador.GestionCliente;
import controlador.GestionComuna;
import java.awt.Color;
import modelo.Comuna;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import modelo.Cliente;
/**
 *
 * @author usuario
 */
public class AgregarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    int xMouse, yMouse;
    GestionCliente gc = new GestionCliente();
    public AgregarCliente() {
        setIcon();
        initComponents();
        btn_actualizar.setEnabled(false);
        GestionComuna gc = new GestionComuna();
        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_menu_cli.setBorder(emptyBorder);
        btn_menu_med.setOpaque(false);
        btn_menu_med.setContentAreaFilled(false);
        btn_menu_med.setBorderPainted(false);
        btn_menu_mas.setOpaque(false);
        btn_menu_mas.setContentAreaFilled(false);
        btn_menu_mas.setBorderPainted(false);
        ArrayList<Comuna> comuna=new ArrayList<>();
        comuna=gc.listarComunas();
        cbo_comuna.addItem("Seleccione");
        for(int i=0;i<comuna.size();i++)
        {
             cbo_comuna.addItem(comuna.get(i).getComuna_desc());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGr_tipo_cli = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_nombre_logo = new javax.swing.JLabel();
        btn_menu_cli = new javax.swing.JButton();
        btn_menu_med = new javax.swing.JButton();
        btn_menu_mas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_rut = new javax.swing.JLabel();
        txt_run = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_nom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_nombre = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_direccion1 = new javax.swing.JLabel();
        cbo_comuna = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        txt_telef = new javax.swing.JTextField();
        lbl_telef = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        rbn_empresa = new javax.swing.JRadioButton();
        lbl_tipo_cli = new javax.swing.JLabel();
        rbn_particular = new javax.swing.JRadioButton();
        btn_agregar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btn_limpiar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setMinimumSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(25, 32, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(25, 32, 40));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        lbl_exit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 805, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        jPanel1.setBackground(new java.awt.Color(25, 32, 40));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo.png"))); // NOI18N

        lbl_nombre_logo.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        lbl_nombre_logo.setForeground(new java.awt.Color(24, 76, 153));
        lbl_nombre_logo.setText("BESTPAWS");

        btn_menu_cli.setBackground(new java.awt.Color(0, 81, 204));
        btn_menu_cli.setFont(new java.awt.Font("Roboto Th", 0, 14)); // NOI18N
        btn_menu_cli.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cliente.png"))); // NOI18N
        btn_menu_cli.setText("Añadir Cliente");
        btn_menu_cli.setBorder(null);
        btn_menu_cli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_cliActionPerformed(evt);
            }
        });

        btn_menu_med.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        btn_menu_med.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_med.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/medico.png"))); // NOI18N
        btn_menu_med.setText("Añadir Medico");
        btn_menu_med.setBorder(null);
        btn_menu_med.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_menu_mas.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        btn_menu_mas.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mascota.png"))); // NOI18N
        btn_menu_mas.setText("Añadir Mascota");
        btn_menu_mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_masActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lbl_nombre_logo))
                        .addComponent(btn_menu_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu_mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu_med, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_logo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_logo)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_logo)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_cli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu_med, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu_mas)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        jPanel2.setBackground(new java.awt.Color(49, 66, 82));

        lbl_titulo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("NUEVO CLIENTE");

        lbl_rut.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_rut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut.setText("RUT");

        txt_run.setBackground(new java.awt.Color(49, 66, 82));
        txt_run.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_run.setForeground(new java.awt.Color(204, 204, 204));
        txt_run.setText(" Ingrese su RUT con guión");
        txt_run.setToolTipText("");
        txt_run.setBorder(null);
        txt_run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_runMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txt_nom.setBackground(new java.awt.Color(49, 66, 82));
        txt_nom.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(204, 204, 204));
        txt_nom.setText(" Ingrese su nombre");
        txt_nom.setToolTipText("");
        txt_nom.setBorder(null);
        txt_nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nomMousePressed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lbl_nombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("NOMBRE COMPLETO");

        txt_dir.setBackground(new java.awt.Color(49, 66, 82));
        txt_dir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_dir.setForeground(new java.awt.Color(204, 204, 204));
        txt_dir.setText(" Ingrese su direccion");
        txt_dir.setToolTipText("");
        txt_dir.setBorder(null);
        txt_dir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_dirMousePressed(evt);
            }
        });
        txt_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dirActionPerformed(evt);
            }
        });

        lbl_direccion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_direccion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direccion.setText("DIRECCIÓN");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lbl_direccion1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_direccion1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direccion1.setText("COMUNA");

        cbo_comuna.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cbo_comuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_comunaActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        txt_telef.setBackground(new java.awt.Color(49, 66, 82));
        txt_telef.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_telef.setForeground(new java.awt.Color(204, 204, 204));
        txt_telef.setText(" Ingrese su teléfono");
        txt_telef.setToolTipText("");
        txt_telef.setBorder(null);
        txt_telef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_telefMousePressed(evt);
            }
        });
        txt_telef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefActionPerformed(evt);
            }
        });

        lbl_telef.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_telef.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telef.setText("TELÉFONO");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txt_email.setBackground(new java.awt.Color(49, 66, 82));
        txt_email.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(204, 204, 204));
        txt_email.setText(" Ingrese su email");
        txt_email.setToolTipText("");
        txt_email.setBorder(null);
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_emailMousePressed(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        lbl_mail.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mail.setText("EMAIL");

        btnGr_tipo_cli.add(rbn_empresa);
        rbn_empresa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rbn_empresa.setForeground(new java.awt.Color(255, 255, 255));
        rbn_empresa.setText("Empresa");
        rbn_empresa.setActionCommand("");
        rbn_empresa.setBorder(null);

        lbl_tipo_cli.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl_tipo_cli.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_cli.setText("TIPO DE CLIENTE");

        btnGr_tipo_cli.add(rbn_particular);
        rbn_particular.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rbn_particular.setForeground(new java.awt.Color(255, 255, 255));
        rbn_particular.setText("Particular");
        rbn_particular.setActionCommand("");
        rbn_particular.setBorder(null);

        btn_agregar.setBackground(new java.awt.Color(49, 66, 82));
        btn_agregar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(49, 66, 82));
        btn_actualizar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        btn_limpiar.setBackground(new java.awt.Color(49, 66, 82));
        btn_limpiar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(49, 66, 82));
        btn_volver.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.setToolTipText("");
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_email)
                            .addComponent(lbl_mail)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbn_particular)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbn_empresa))
                                    .addComponent(lbl_tipo_cli)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(btn_actualizar)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_limpiar)
                                    .addComponent(btn_agregar)
                                    .addComponent(btn_volver))
                                .addGap(103, 103, 103))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_telef)
                                .addComponent(lbl_telef)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_dir)
                                    .addComponent(lbl_direccion)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_direccion1)
                                    .addComponent(cbo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nom)
                                    .addComponent(lbl_nombre)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_run, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(lbl_rut)
                                    .addComponent(lbl_titulo)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator6))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo)
                    .addComponent(btn_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rut)
                    .addComponent(btn_volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_run, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(lbl_direccion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_telef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mail)
                    .addComponent(lbl_tipo_cli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbn_empresa)
                    .addComponent(rbn_particular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_agregar)
                        .addComponent(btn_actualizar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 650, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu_cliActionPerformed

    private void btn_menu_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_masActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu_masActionPerformed

    private void txt_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dirActionPerformed

    private void cbo_comunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_comunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_comunaActionPerformed

    private void txt_telefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:  
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        // TODO add your handling code here:
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        // TODO add your handling code here:
        exitBtn.setBackground(new java.awt.Color(25, 32, 40));
    }//GEN-LAST:event_exitBtnMouseExited

    private void txt_runMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_runMousePressed
        // TODO add your handling code here:
        if(txt_run.getText().equals(" Ingrese su RUT con guión")){
            txt_run.setText("");
            txt_run.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_runMousePressed

    private void txt_nomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nomMousePressed
        // TODO add your handling code here:
        if(txt_nom.getText().equals(" Ingrese su nombre")){
            txt_nom.setText("");
            txt_nom.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_nomMousePressed

    private void txt_dirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dirMousePressed
        // TODO add your handling code here:
        if(txt_dir.getText().equals(" Ingrese su direccion")){
            txt_dir.setText("");
            txt_dir.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_dirMousePressed

    private void txt_telefMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_telefMousePressed
        // TODO add your handling code here:
        if(txt_telef.getText().equals(" Ingrese su teléfono")){
            txt_telef.setText("");
            txt_telef.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_telefMousePressed

    private void txt_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMousePressed
        // TODO add your handling code here:
        if(txt_email.getText().equals(" Ingrese su email")){
            txt_email.setText("");
            txt_email.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_emailMousePressed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        txt_run.setForeground(new java.awt.Color(204,204,204));
        txt_run.setText(" Ingrese su RUT con guión");
        txt_nom.setForeground(new java.awt.Color(204,204,204));
        txt_nom.setText(" Ingrese su nombre");
        txt_dir.setForeground(new java.awt.Color(204,204,204));
        txt_dir.setText(" Ingrese su direccion");
        txt_telef.setForeground(new java.awt.Color(204,204,204));
        txt_telef.setText("Ingrese su teléfono");
        txt_email.setForeground(new java.awt.Color(204,204,204));
        txt_email.setText("Ingrese su email");
        btnGr_tipo_cli.clearSelection();
        cbo_comuna.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
//        if(txt_run.getText().equals(" Ingrese su RUT con guión") || txt_nom.getText().equals(" Ingrese su nombre") 
//                || txt_dir.getText().equals(" Ingrese su direccion") || txt_telef.getText().equals(" Ingrese su teléfono")
//                || txt_email.getText().equals(" Ingrese su email") || rbn_empresa.isSelected() == false
//                || rbn_particular.isSelected() == false || cbo_comuna.getSelectedIndex() == 0){
//            JOptionPane.showMessageDialog(this, "Debe rellenar los campos","",JOptionPane.WARNING_MESSAGE);
            System.out.println(txt_run.getText() + ","+txt_nom.getText()+ ","+txt_dir.getText()+ ","+txt_telef.getText()
                    + ","+txt_email.getText()+ ",BTNGR EMPRESA:"+rbn_empresa.isSelected()+ ",BTNGR particular:"+rbn_particular.isSelected()+
                    ",COMUNA "+cbo_comuna.getSelectedIndex()+"...");
        if (txt_run.getText().isEmpty() || txt_nom.getText().isEmpty()  
                || txt_dir.getText().isEmpty() || txt_telef.getText().isEmpty() 
                || txt_email.getText().isEmpty() || rbn_empresa.isSelected() == false
                && rbn_particular.isSelected() == false || cbo_comuna.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos","",JOptionPane.WARNING_MESSAGE);
            System.out.println(txt_run.getText() + ","+txt_nom.getText()+ ","+txt_dir.getText()+ ","+txt_telef.getText()
                    + ","+txt_email.getText()+ ",BTNGR EMPRESA:"+rbn_empresa.isSelected()+ ",BTNGR particular:"+rbn_particular.isSelected()+
                    ",COMUNA "+cbo_comuna.getSelectedItem());
        }else{
            String rut_cli = txt_run.getText();
            String nombre_cli = txt_nom.getText();
            String direccion_cli = txt_dir.getText();
            Comuna comuna = new Comuna();
            int comuna_id = cbo_comuna.getSelectedIndex();
            int telefono_cli = Integer.parseInt(txt_telef.getText());
            String email_cli = txt_email.getText();
            char tipo_cli = ' ';
            if(rbn_empresa.isSelected() == true){
                tipo_cli = 'E';
            }else{
                tipo_cli = 'P';
            }
            Cliente cliente = new Cliente(rut_cli, nombre_cli, direccion_cli, email_cli, comuna_id, telefono_cli, tipo_cli);
            boolean mensaje = gc.agregarCliente(cliente);
            if(mensaje == true){
                JOptionPane.showMessageDialog(this, "Cliente Ingresado");
                btn_limpiarActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(this, "Cliente No Ingresado");
            }             
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(rootPaneCheckingEnabled);
        dispose(); 
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup btnGr_tipo_cli;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_menu_cli;
    private javax.swing.JButton btn_menu_mas;
    private javax.swing.JButton btn_menu_med;
    private javax.swing.JButton btn_volver;
    public static javax.swing.JComboBox<String> cbo_comuna;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_direccion1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombre_logo;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JLabel lbl_telef;
    private javax.swing.JLabel lbl_tipo_cli;
    private javax.swing.JLabel lbl_titulo;
    public static javax.swing.JRadioButton rbn_empresa;
    public static javax.swing.JRadioButton rbn_particular;
    public static javax.swing.JTextField txt_dir;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_nom;
    public static javax.swing.JTextField txt_run;
    public static javax.swing.JTextField txt_telef;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/favicon.png")));
    }



}
