/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import conexionBD.ConexionOracle;
import controlador.GestionComuna;
import java.awt.Color;
import modelo.Comuna;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import java.awt.Toolkit;
/**
 *
 * @author usuario
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    int xMouse, yMouse;
    
    public Home() {
        initComponents();
        setIcon();
        btn_menu_cli.setOpaque(false);
        btn_menu_cli.setContentAreaFilled(false);
        btn_menu_cli.setBorderPainted(false);
        btn_menu_med.setOpaque(false);
        btn_menu_med.setContentAreaFilled(false);
        btn_menu_med.setBorderPainted(false);
        btn_menu_mas.setOpaque(false);
        btn_menu_mas.setContentAreaFilled(false);
        btn_menu_mas.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGr_tipo_cli = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_nombre_logo = new javax.swing.JLabel();
        btn_menu_cli = new javax.swing.JButton();
        btn_menu_med = new javax.swing.JButton();
        btn_menu_mas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setMinimumSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(25, 32, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(25, 32, 40));

        lbl_exit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 805, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        jPanel1.setBackground(new java.awt.Color(25, 32, 40));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo.png"))); // NOI18N

        lbl_nombre_logo.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        lbl_nombre_logo.setForeground(new java.awt.Color(24, 76, 153));
        lbl_nombre_logo.setText("BESTPAWS");

        btn_menu_cli.setBackground(new java.awt.Color(0, 81, 204));
        btn_menu_cli.setFont(new java.awt.Font("Roboto Th", 0, 14)); // NOI18N
        btn_menu_cli.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cliente.png"))); // NOI18N
        btn_menu_cli.setText("Añadir Cliente");
        btn_menu_cli.setBorder(null);
        btn_menu_cli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu_cliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu_cliMouseExited(evt);
            }
        });
        btn_menu_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_cliActionPerformed(evt);
            }
        });

        btn_menu_med.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        btn_menu_med.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_med.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/medico.png"))); // NOI18N
        btn_menu_med.setText("Añadir Medico");
        btn_menu_med.setBorder(null);
        btn_menu_med.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu_medMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu_medMouseExited(evt);
            }
        });

        btn_menu_mas.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        btn_menu_mas.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mascota.png"))); // NOI18N
        btn_menu_mas.setText("Añadir Mascota");
        btn_menu_mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu_masMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu_masMouseExited(evt);
            }
        });
        btn_menu_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_masActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lbl_nombre_logo))
                        .addComponent(btn_menu_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu_mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu_med, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_logo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_logo)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_logo)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_cli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu_med, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu_mas)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        jPanel2.setBackground(new java.awt.Color(49, 66, 82));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 650, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_cliActionPerformed
        // TODO add your handling code here:
        AgregarCliente agregarcliente = new AgregarCliente();
        agregarcliente.setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_btn_menu_cliActionPerformed

    private void btn_menu_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_masActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu_masActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:  
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        // TODO add your handling code here:
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        // TODO add your handling code here:
        exitBtn.setBackground(new java.awt.Color(25, 32, 40));
    }//GEN-LAST:event_lbl_exitMouseExited

    private void btn_menu_cliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_cliMouseEntered
        // TODO add your handling code here:
        btn_menu_cli.setOpaque(true);
        btn_menu_cli.setContentAreaFilled(true);
        btn_menu_cli.setBorderPainted(true);
        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_menu_cli.setBorder(emptyBorder);
        btn_menu_cli.setBackground(new java.awt.Color(0, 81, 204));
    }//GEN-LAST:event_btn_menu_cliMouseEntered

    private void btn_menu_cliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_cliMouseExited
        // TODO add your handling code here:
        btn_menu_cli.setOpaque(false);
        btn_menu_cli.setContentAreaFilled(false);
        btn_menu_cli.setBorderPainted(false);
        btn_menu_cli.setBackground(new java.awt.Color(25, 32, 40));
    }//GEN-LAST:event_btn_menu_cliMouseExited

    private void btn_menu_medMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_medMouseEntered
        // TODO add your handling code here:
        btn_menu_med.setOpaque(true);
        btn_menu_med.setContentAreaFilled(true);
        btn_menu_med.setBorderPainted(true);
        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_menu_med.setBorder(emptyBorder);
        btn_menu_med.setBackground(new java.awt.Color(0, 81, 204));
    }//GEN-LAST:event_btn_menu_medMouseEntered

    private void btn_menu_medMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_medMouseExited
        // TODO add your handling code here:
        btn_menu_med.setOpaque(false);
        btn_menu_med.setContentAreaFilled(false);
        btn_menu_med.setBorderPainted(false);
        btn_menu_med.setBackground(new java.awt.Color(25, 32, 40));
    }//GEN-LAST:event_btn_menu_medMouseExited

    private void btn_menu_masMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_masMouseEntered
        // TODO add your handling code here:
        btn_menu_mas.setOpaque(true);
        btn_menu_mas.setContentAreaFilled(true);
        btn_menu_mas.setBorderPainted(true);
        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_menu_mas.setBorder(emptyBorder);
        btn_menu_mas.setBackground(new java.awt.Color(0, 81, 204));
    }//GEN-LAST:event_btn_menu_masMouseEntered

    private void btn_menu_masMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_masMouseExited
        // TODO add your handling code here:
        btn_menu_mas.setOpaque(false);
        btn_menu_mas.setContentAreaFilled(false);
        btn_menu_mas.setBorderPainted(false);
        btn_menu_mas.setBackground(new java.awt.Color(25, 32, 40));
    }//GEN-LAST:event_btn_menu_masMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup btnGr_tipo_cli;
    private javax.swing.JButton btn_menu_cli;
    private javax.swing.JButton btn_menu_mas;
    private javax.swing.JButton btn_menu_med;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombre_logo;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/favicon.png")));
    }




}
